-- AlterTable
ALTER TABLE "ApiRoute" ADD COLUMN     "avgResponseMs" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fails" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "successes" INTEGER NOT NULL DEFAULT 0;
